# RECOMMENDER SYSTEMM - UBCF
This project aims to randomly generate user-item matrix data and recommend a rating based on User-based Collaborative Filtering (UBCF)

**Input**: User-matrix item (with a blank rating to predict)\
**Output**: The rating for the empty node

## Step 1: Generate and initialize input user-item matrix

**User-item matrix**: As an example above an user-item matrix has this format:
|       | Item 1  | Item 2  | Item 3  |   ...   | Item n |
|:---   | :----:  | :----:  | :----:  |  :----: |   ---: |
|User 1 |    4    |    1    |    0    |   ...   |    5   |
|User 2 |    5    |    2    |    2    |   ...   |    3   |
|User 3 |    2    |    5    |    1    |   ...   |    1   |
|...    |   ...   |   ...   |   ...   |   ...   |   ...  |
|User m |    3    |    5    |    5    |   ...   |    4   |
Note: '0' value represents the empty value which needs to be predicted

The functions **empty_node, generate_user_item_matrix, devalue_matrix** serve the purposes to complete the generation of an user-item matrix

In [1]:
import numpy as np
import random
import copy
import time

In [2]:
start = time.time()

# This function generates a random position for the empty value in user-item matrix
def empty_node(num_row, num_col):
    """
    Generate a random position in a range between the start and stop numbers
    
    Args:
    start -- the beginning number
    end -- the ending number
    
    Returns:
    (row, col) -- a pair of generated row and column
    """
    row = random.randint(0, num_row - 1)
    col = random.randint(0, num_col - 1)
    return row, col

In [3]:
# This function generates a random user-item matrix
def generate_user_item_matrix(num_row, num_col):
    """
    It creates a matrix with 'num_row' rows and 'num_col' columns,
    whose values range between from 1 to 5 stars (inclusive)
    
    Args:
    num_row -- number of rows
    num_col -- number of columns
    
    Returns:
    np.ndarry -- the resulting numpy matrix
    """
    one_star = 1
    five_star = 5
        
    user_item_matrix = np.random.randint(one_star, five_star + 1, size=(num_row, num_col))
        
    return user_item_matrix

In [4]:
# This function empties a value in user-item matrix
def devalue_matrix(user_item_matrix, empty_node):
    """It devalues a value in user-item matrix, where the position is based on 'empty node' parameter
    
    Args:
    user_item_matrix -- the user-item matrix
    empty_node -- the provided position to devalue
    
    Returns:
    np.ndarray -- new user-item matrix with a '0' value
    """
    
    row, col = empty_node
    user_item_matrix[row, col] = 0
    return user_item_matrix

In [5]:
# Initialize input data
num_users = 1000
num_items = 5000
row_pos, col_pos = empty_node(num_users, num_items)
empty_node = (row_pos, col_pos)
user_item_matrix = generate_user_item_matrix(num_users, num_items)
user_item_matrix = devalue_matrix(user_item_matrix, empty_node)

In [6]:
user_item_matrix

array([[4, 3, 3, ..., 5, 1, 2],
       [1, 3, 1, ..., 5, 5, 3],
       [3, 5, 2, ..., 4, 4, 2],
       ...,
       [1, 1, 2, ..., 4, 2, 4],
       [2, 2, 3, ..., 2, 3, 1],
       [5, 2, 1, ..., 5, 2, 2]])

In [7]:
# This block is used as an example to test your result
# user_item_matrix = np.array([[5,4,1,4,0],
#                             [3,1,2,3,3],
#                             [4,3,4,3,5],
#                             [3,3,1,5,4],
#                             [1,5,5,2,1]])
# num_users = 5
# num_items = 5
# empty_node = (0, 4)
# Result: unrounded predicted rating = 4.24047254

## Step 2: Calculate Similarity values among Users

This step focuses on calculating the average rating of users' ratings, its variance, then the similarity of the neighborhoods with the user needs to be predicted for a item

**Step 2.1**: To calculate mean, the average rating values of users are computed by suming all ratings of a user then divide it by its number of ratings:
|       |  r_mean   |
|:---   |  :----:   |
|User 1 |    3.6    |
|User 2 |    2.7    |
|User 3 |    4.2    |
|...    |    ...    |
|User m |    2.9    |
Note: The number of ratings does not count '0' value(s)

In [8]:
# This function calculates mean of ratings among users
def calculate_mean(user_item_matrix, num_row):
    """ Calculate the mean of ratings among users,
    in which '0' values are ignored
    
    Args:
    user_item_matrix -- the input matrix data
    num_row -- number of rows (number of users)
    
    Returns:
    mean_rs -- the average array of ratings
    """
    mean_rs = []
    
    for i in range(num_row):
        # Get the ratings array of an user
        user_rating = user_item_matrix[i]
        
        # Get all values excluding zero numbers
        non_zero_values = user_rating[user_rating != 0]
        
        # Calculate mean
        mean = np.mean(non_zero_values) 
        mean_rs.append(mean)
    
    # Change to numpy array and reshape to (m, 1)
    mean_rs = np.array(mean_rs).reshape(num_row, 1)

    return mean_rs

In [9]:
# Get mean matrix
mean_rs = calculate_mean(user_item_matrix, num_users)

In [10]:
mean_rs

array([[3.0118    ],
       [2.9858    ],
       [3.0086    ],
       [3.0182    ],
       [3.007     ],
       [2.9986    ],
       [2.9972    ],
       [3.0456    ],
       [3.0056    ],
       [3.0294    ],
       [2.9728    ],
       [2.9692    ],
       [3.0004    ],
       [3.0224    ],
       [3.0188    ],
       [3.0066    ],
       [2.9476    ],
       [2.9936    ],
       [3.0206    ],
       [3.0456    ],
       [3.0332    ],
       [2.9856    ],
       [2.997     ],
       [2.9898    ],
       [3.0066    ],
       [2.9908    ],
       [3.0192    ],
       [2.9878    ],
       [3.0094    ],
       [2.9804    ],
       [2.971     ],
       [3.017     ],
       [3.0276    ],
       [3.0084    ],
       [3.        ],
       [2.9678    ],
       [3.0392    ],
       [3.0144    ],
       [3.        ],
       [3.02420484],
       [2.9872    ],
       [2.9996    ],
       [3.0282    ],
       [3.0208    ],
       [3.002     ],
       [3.0122    ],
       [3.008     ],
       [2.996

**Step 2.2**: To calculate similarity, apply the operation for `PEARSON_CORRELATION`:
<center>
$ sim(u,v) = \frac{\sum{(r_{u,i} - \bar{r_u})(r_{v,i} - \bar{r_v})}}{\sqrt{\sum{(r_{u,i} - \bar{r_u})^2} \cdot \sum{(r_{v,i} - \bar{r_v})^2}}} $
</center>

In [11]:
# This function computes standard deviation of each user's rating
def std(user_item_matrix, mean_rs, num_users, num_items):
    """
    Args:
    user_item_matrix -- the input user-item matrix
    mean_rs -- the mean matrix of ratings
    num_users -- number of users
    num_items -- number of items
    
    Returns:
    std -- the standard deviation matrix of each user's ratings
    """
    stds = []
    
    for i in range(num_users):
        # Create an empty list to save intermediate values
        tmp_var = []
        
        # The 'count' parameter counts non-zero values in an array
        count = num_items
        
        # Get mean_r value of an user
        mean = mean_rs[i]
        
        # For each item in a list of user's rating
        for j in range(num_items):
            # Get r value of an item
            value = user_item_matrix[i][j]
            
            # If there's a 0 in the array, decrease the number of count by 1
            # Then ignore this element
            if value == 0:
                num_items -= 1
                continue
                
            # Compute the operation inside the square root
            tmp_var.append((value - mean) ** 2)
            
        # Sum all the values inside the square root, and get it squared root
        std = np.sqrt(np.sum(tmp_var))
        
        # Append the computed variance to the variance list
        stds.append(std)
        
    # Change the list to numpy array and reshape the variance list
    stds = np.array(stds).reshape(num_users, 1)
        
    return stds

In [12]:
# Get standard deviation matrix of users' ratings
stds = std(user_item_matrix, mean_rs, num_users, num_items)

In [13]:
stds

array([[100.70900556],
       [ 99.33776623],
       [ 99.48180839],
       [ 99.57581935],
       [ 99.77351853],
       [ 99.94493584],
       [ 99.48849582],
       [100.19782034],
       [100.74643021],
       [ 99.04886774],
       [100.01150334],
       [100.65414448],
       [100.84641392],
       [ 99.25467848],
       [100.46010551],
       [ 99.65331003],
       [100.64924838],
       [100.22871445],
       [100.41353594],
       [100.81469734],
       [ 99.68193818],
       [100.42391747],
       [ 99.05026502],
       [100.16226735],
       [100.37321455],
       [100.46679451],
       [100.21056232],
       [ 99.84115284],
       [ 99.62207687],
       [ 98.89428295],
       [ 99.8238198 ],
       [ 99.57687985],
       [100.28056242],
       [ 99.63757926],
       [100.        ],
       [ 99.61835072],
       [100.03157901],
       [ 99.83467935],
       [ 99.69954864],
       [ 99.37842429],
       [100.41529682],
       [ 99.96498587],
       [100.28527212],
       [100

In [14]:
# This function calculates the covariance of Pearson correlation coefficient (nominator of the expression)
def covariance(user_item_matrix, mean_rs, stds, num_users, num_items, empty_node):
    """
    Args:
    user_item_matrix -- the user-item matrix
    mean_rs -- the mean matrix of ratings
    stds -- the standard deviation matrix of ratings
    num_users -- the number of users
    num_items -- the number of items
    empty_node -- the position of the '0' value
    
    Returns:
    covariances -- the covariance matrix of each user's rating
    """
    covariances = []
    
    # Get the position of the empty node
    u_row, u_col = empty_node
    
    # Get r_u list and mean_r_u value
    r_u = user_item_matrix[u_row]
    mean_r_u = mean_rs[u_row][0]
    
    # For each user
    for i in range(num_users):
        # Create an empty list to save intermediate values
        tmp_var = []
        
        # Get r_v list and mean_r_v value
        r_v = user_item_matrix[i]
        mean_r_v = mean_rs[i][0]
        
        # If it reaches the position of the empty node (v == u)
        # Then assigns the covariance as NaN and skips to the next user 
        if i == u_row:
            covariances.append(np.nan)
            continue
            
        # For each item, compute multiplication list
        for j in range(num_items):
            # If there's an empty node in a column, then skips the item
            if j == u_col:
                continue
            
            # Compute multiplication (nominator)
            mul = (r_u[j] - mean_r_u) * (r_v[j] - mean_r_v)
            
            # Append the multiplication value to save in the list
            tmp_var.append(mul)
        
        # Sum all elements in the covariance list
        covariance = np.sum(tmp_var)
        
        # Add the computed covariance to the list of covariances of users
        covariances.append(covariance)
        
    # Change the list to numpy array and reshape the covariance list
    covariances = np.array(covariances).reshape(num_users, 1)
        
    return covariances

In [15]:
covariances = covariance(user_item_matrix, mean_rs, stds, num_users, num_items, empty_node)

In [16]:
covariances

array([[-1.34280856e+01],
       [-2.23056611e+01],
       [-3.15065013e+02],
       [ 2.35821564e+02],
       [ 1.24177035e+02],
       [-2.37830566e+02],
       [-1.47709542e+02],
       [-6.65671134e+01],
       [-2.01726145e+02],
       [-6.45339068e+01],
       [ 2.77340268e+02],
       [-1.32240448e+01],
       [ 7.50000000e+01],
       [-2.61710942e+02],
       [-1.02994599e+01],
       [-7.57745549e+01],
       [ 4.93900780e+01],
       [-1.02254451e+01],
       [-1.81541508e+02],
       [ 4.24328866e+01],
       [ 1.89577916e+01],
       [ 2.32742749e+02],
       [-2.26369274e+01],
       [ 6.21860372e+01],
       [ 2.01770354e+01],
       [-1.63910782e+02],
       [ 3.66279256e+01],
       [-1.46475095e+02],
       [ 8.88139628e+01],
       [-8.36763353e+01],
       [-2.55466093e+02],
       [ 4.59425885e+01],
       [-1.26340268e+02],
       [ 4.70318064e+01],
       [-3.05951590e+02],
       [ 1.69872775e+02],
       [ 2.20255851e+02],
       [-4.37911582e+01],
       [ 1.2

In [17]:
# This function computes the similarities between users
def similarity(user_item_matrix, covariances, stds, num_users, empty_node):
    """
    Args:
    user_item_matrix -- the user-item matrix
    covariances -- the arrays saving covariance values between users
    stds -- standard deviation values of each user
    num_users -- number of users
    empty_node -- the position of the '0' value
    
    Returns:
    similarity -- the similarity matrix
    """
    # Similarity list
    similarity = []
    
    # Get position of the u user and its standard deviation
    u_row, u_col = empty_node
    std_u = stds[u_row]
    
    # For each user v, calculate its similarity to u
    for i in range(num_users):
        # In case the user u is the same as v (v == u)
        # Then assigns the covariance as NaN and skips to the next user
        if i == u_row:
            similarity.append(-np.inf)
            continue
            
        # Get covariance and standard deviation values of neighbor user v
        cov_u_v = covariances[i]
        std_v = stds[i]
        
        # Compute the similarity value
        value = cov_u_v / (std_u * std_v)
        similarity.append(value[0])
        
    similarity = np.array(similarity).reshape(num_users, 1)
    
    return similarity

In [18]:
similarity = similarity(user_item_matrix, covariances, stds, num_users, empty_node)

In [19]:
similarity

array([[-1.34169465e-03],
       [-2.25948053e-03],
       [-3.18687039e-02],
       [ 2.38307396e-02],
       [ 1.25237357e-02],
       [-2.39449960e-02],
       [-1.49397586e-02],
       [-6.68512211e-03],
       [-2.01483932e-02],
       [-6.55611157e-03],
       [ 2.79042831e-02],
       [-1.32202767e-03],
       [ 7.48356780e-03],
       [-2.65325376e-02],
       [-1.03164129e-03],
       [-7.65137626e-03],
       [ 4.93784064e-03],
       [-1.02659219e-03],
       [-1.81924660e-02],
       [ 4.23532381e-03],
       [ 1.91372338e-03],
       [ 2.33209852e-02],
       [-2.29969229e-03],
       [ 6.24736139e-03],
       [ 2.02277425e-03],
       [-1.64169649e-02],
       [ 3.67795759e-03],
       [-1.47625742e-02],
       [ 8.97084908e-03],
       [-8.51411200e-03],
       [-2.57517635e-02],
       [ 4.64263820e-03],
       [-1.26774798e-02],
       [ 4.74981161e-03],
       [-3.07865206e-02],
       [ 1.71590139e-02],
       [ 2.21563503e-02],
       [-4.41380252e-03],
       [ 1.3

In [20]:
# This functions finds k-nearest neighbors to the user u
def k_nearest_neighbors(similarity, num_users, k):
    """
    Args: 
    similarity -- the similarity array between neighbor users to user u
    num_users -- number of users
    k -- the number to find k-largest similarity values
    
    Returns:
    most_similar -- k-size array of most similar neighbors to user u (a list of (similarity value, index))
    """
    most_similar = []
    
    # Copy the current similarity array
    sim = copy.deepcopy(similarity)
    
    # Reshape a (n, 1) array to (1, n) array
    sim = sim.reshape(1, num_users)
    
    # An array for intermediate calculations
    new_arr = []
    
    # For each usser
    for i in range(num_users):
        # Pair the similarity values and their index
        # Then assign it to a new array
        tmp = (sim[0][i], i)
        new_arr.append(tmp)

    # Sort the new array by their similarity values
    new_arr = sorted(new_arr)
    
    # Get the most similar values to the user u
    # in which the largest similarities are sorted ascendingly
    most_similar = new_arr[-k:]
    
    return most_similar

In [21]:
k = 2
most_similar = k_nearest_neighbors(similarity, num_users, k)

In [22]:
most_similar

[(0.03748452211985635, 581), (0.04100996122137901, 867)]

## Step 3: Predict

After getting all means, standard deviations, covariances, and similarities, let's predict the rating of user u for the empty item

In [23]:
# This function predicts the rating of user u for item i
def predict(user_item_matrix, most_similar, mean_rs, empty_node, k):
    """
    Args:
    user_item_matrix -- the user-item matrix
    most_similar -- k-size array of most similar neighbors to user u (a list of (similarity value, index))
    mean_rs -- the mean matrix of ratings
    empty_node -- the position of the '0' value
    k -- the number of k-nearest neighbors
    
    Returns:
    predicted_rating -- the predicting rating of user u for the item i
    """
    # Get the position of the '0' value
    u_row, u_col = empty_node
    
    # Get the mean value of user u
    mean_r_u = mean_rs[u_row]
    
    # Initialize numerator and denominator values of the prediction expression
    numerator = 0
    denominator = 0
    
    # For each nearest neighbor
    for i in range(k):
        # Get the similarity value and its index
        similarity, s_index = most_similar[i]
        
        # Get the rating of neighbor user v for item i (at u_col)
        r_v = user_item_matrix[s_index][u_col]
        
        # Get the mean rating of neighbor user v for item i (at u_col)
        mean_r_v = mean_rs[s_index]
        
        # Compute the numerator and denominator in the expression
        numerator += similarity * (r_v - mean_r_v)
        denominator += similarity
        
    # Compute the predicted rating of user u for item i    
    predicted_rating = mean_r_u + numerator / denominator
    return predicted_rating

In [24]:
# Get the predicted rating of user u for item i 
predicted_rating = predict(user_item_matrix, most_similar, mean_rs, empty_node, k)
predicted_rating = int(predicted_rating)

In [25]:
u_row, u_col = empty_node
print(user_item_matrix)
print(f'User {u_row} is predicted to rate the item {u_col} with {predicted_rating} star(s)')

end = time.time()
print(f'The algorithm run in {int(end - start)} second(s)')

[[4 3 3 ... 5 1 2]
 [1 3 1 ... 5 5 3]
 [3 5 2 ... 4 4 2]
 ...
 [1 1 2 ... 4 2 4]
 [2 2 3 ... 2 3 1]
 [5 2 1 ... 5 2 2]]
User 39 is predicted to rate the item 2651 with 2 star(s)
The algorithm run in 17 second(s)
